spring:
  application:
    name: Stacklite Backend
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:stacklite
    driver-class-name: org.h2.Driver
    username: sa
    password: password